#!/bin/bash
#
# Copyright (c) 2012, Thiago Farina
#
# 2013-24-12 Thiago Farina <tfarina@chromium.org>
#

# Die if any command dies.
set -e

NUM_JOBS="$(grep -c "^processor" /proc/cpuinfo)"

# First: Sync Chromium repo.

cd "${HOME}/blink/src"
echo "Syncing Chromium..."
git pull --rebase

# Then: Sync Blink repo.

cd "${HOME}/blink/src/third_party/WebKit"
echo "Syncing Blink..."
git pull --rebase

GYP_CHROMIUM_NO_ACTION=1 gclient sync -j"${NUM_JOBS}"
