#!/bin/bash

#
# https://github.com/davidarrieta/dotfiles/blob/master/scripts/.scripts/colorblocks
#

while :; do
  printf "\x1b[48;5;$((RANDOM % 255))m \x1b[48;5;$((RANDOM % 255))m \x1b[48;5;$((RANDOM % 255))m \x1b[48;5;$((RANDOM % 255))m \x1b[48;5;$((RANDOM % 255))m \x1b[48;5;$((RANDOM % 255))m \x1b[48;5;$((RANDOM % 255))m \x1b[48;5;$((RANDOM % 255))m "
done
