#!/bin/bash
#
# Copyright (c) 2013, Thiago Farina
#
# 2013-07-13 Thiago Farina <tfarina@chromium.org>
#
# Die if any command dies.
set -e

cd $HOME/chromium/src

# Default build type is Debug.
CR_BUILDTYPE=Debug

PLATFORM="$(uname -s | tr 'A-Z' 'a-z')"

if [[ $PLATFORM == "linux" ]]; then
  NUM_JOBS="$(grep -c "^processor" /proc/cpuinfo)"
elif [[ $PLATFORM == "darwin" ]]; then
  NUM_JOBS="$(sysctl -n hw.ncpu)"
fi

while getopts ":t:" opt ; do
        case $opt in
                t) CR_BUILDTYPE="$OPTARG";;
        esac
done
shift $(( OPTIND - 1 ))

# Default target is chrome.
TARGETS="$@"

if [ -z "$TARGETS" ]; then
  TARGETS="chrome"
fi

time ninja -C out/"${CR_BUILDTYPE}" -k4 -j"${NUM_JOBS}" $TARGETS
