#!/bin/bash
#
# Copyright (c) 2013, Thiago Farina
#
# 2013-07-13 Thiago Farina <tfarina@chromium.org>
#
# Die if any command dies.
set -e

CR_DIR="${HOME}"/chromium/src/
cd "${CR_DIR}"

# Default build type is Debug.
CR_BUILDTYPE=Debug

NUM_JOBS="$(grep -c "^processor" /proc/cpuinfo)"

# Default target is chrome.
TARGETS="$@"

if [ -z "$TARGETS" ]; then
  TARGETS="chrome"
fi

time ninja -C out_cros/"${CR_BUILDTYPE}" -k4 -j"${NUM_JOBS}" $TARGETS 2>&1 | tee ../errors
