#!/bin/bash
#
# Copyright (c) 2014, Thiago Farina
#
# 2014-02-09 Thiago Farina <tfarina@chromium.org>
#
# Die if any command dies.
set -e

gdb --args out_aura/Debug/$1 --no-sandbox --renderer-cmd-prefix='xterm -title renderer -e gdb --args'
