#!/bin/bash

#set -e

CR_DIR="${HOME}"/chromium/src/
CR_CONFIG=$1
shift 1 # move the args so that $@ only passes args after "runtest <target>"

if [ "$CR_CONFIG" == "" ]; then
  "${CR_DIR}"/build/gyp_chromium
elif [ "$CR_CONFIG" == "cros" ]; then
  "${CR_DIR}"/build/gyp_chromium -Dchromeos=1 -Goutput_dir=out_cros
elif [ "$CR_CONFIG" == "android" ]; then
  "${CR_DIR}"/build/gyp_chromium -DOS=android -Goutput_dir=out_android
elif [ "$CR_CONFIG" == "help" ]; then
  echo "Usage: cr-gyp <cros|android>"
fi
