#!/bin/bash
#
# Copyright (c) 2013, Thiago Farina
#
# 2013-24-12 Thiago Farina <tfarina@chromium.org>
#
# Die if any command dies.
set -e

CR_DIR="${HOME}"/chromium/src/

# Default build type is Debug.
CR_BUILDTYPE=Debug

# Default target is chrome.
TARGETS="$1"

if [ -z "$TARGETS" ]; then
  TARGETS="chrome"
fi

"${CR_DIR}"/out_aura/"${CR_BUILDTYPE}"/$TARGETS --no-sandbox
