#!/bin/bash
#
# Copyright (c) 2012, Thiago Farina
#
# 2012-09-01 Thiago Farina <tfarina@chromium.org>
#

# Die if any command dies.
set -e

NUM_JOBS="$(grep -c "^processor" /proc/cpuinfo)"

cd "${HOME}/chromium/src"

git pull --rebase
GYP_CHROMIUM_NO_ACTION=1 gclient sync -j"${NUM_JOBS}" --nohooks
