#!/usr/bin/env bash
# Credits due to this reddit post:
# https://www.reddit.com/r/bspwm/comments/aejyze/tip_show_sxhkd_keybindings_with_fuzzy_search/
# Source: https://gitlab.com/japorized/bin/-/blob/master/rofi-sxhkd-cheatsheet

_rofi() {
  rofi -dmenu -i -p "sxhkd cheatsheet" -no-show-icons -l 10 "$@"
}

cat $HOME/.config/sxhkd/sxhkdrc \
  | awk '/^[a-z]/ && last {print $0,"===",last} {last=""} /^#/{last=$0}' \
  | column -t -s "===" \
  | _rofi
