#!/bin/bash

# Start qemu
qemu-system-i386 -cdrom en_windows_xp_professional_with_service_pack_3_x86_cd_vl_x14-73974.iso \
		 -hda winxpsp3.img \
		 -m 1024 \
		 -boot d \
		 -net nic,model=pcnet \
		 -net user \
		 -smb /srv/samba/share/ \
		 -soundhw ac97 \
		 -usb
