#!/usr/bin/env bash

# https://github.com/cramermarius/rofi-menus/blob/master/scripts/powermenu.sh

# Options to be displayed.
logout="Logout"
restart="Restart"
shutdown="Shutdown"

# Options passed into a variable.
options="$logout\n$restart\n$shutdown"

chosen="$(echo -e "$options" | rofi -lines 8 -dmenu -p "Session:")"

case $chosen in
    $logout)
        if [[ "$DESKTOP_SESSION" == "xfce" ]]; then
	    xfce4-session-logout --logout
        elif [[ "$DESKTOP_SESSION" == "bspwm" ]]; then
	    bspc quit
	fi
        ;;
    $restart)
	systemctl reboot;;
    $shutdown)
	systemctl poweroff;;
esac
