#!/usr/bin/env bash

# https://github.com/cramermarius/rofi-menus/blob/master/scripts/powermenu.sh

# Options to be displayed.
option0="Logout"
option1="Restart"
option2="Shutdown"

# Options passed into a variable.
options="$option0\n$option1\n$option2"

chosen="$(echo -e "$options" | rofi -lines 8 -dmenu -p "Session:")"

case $chosen in
    $option0)
	bspc quit;;
    $option1)
	systemctl reboot;;
    $option2)
	systemctl poweroff;;
esac
