#!/bin/bash

STEP=5
BIGSTEP=25

case "$1" in
    toggle)
	pactl set-sink-mute 0 toggle
        ;;
    raise)
	pactl set-sink-volume 0 +$STEP%
        ;;
    lower)
	pactl set-sink-volume 0 -$STEP%
	;;
    strong_raise)
	pactl set-sink-volume 0 +$BIGSTEP%
        ;;
    strong_lower)
	pactl set-sink-volume 0 -$BIGSTEP%
        ;;
    *)
	echo "Usage: $0 {toggle|raise|lower|strong_raise|strong_lower}"
	exit 2
esac
